version: "3.8"

services:
  segmentation-service:
    container_name: segmentation-container
    image: p8-segmentation-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - "./cle_gcp.json:/app/cle_gcp.json"
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/app/cle_gcp.json
    restart: always
